// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  CommvaultOnPrem: [{ type: 'autogenerated', dirName: 'commvault/commvault-on-prem' }],
  CommvaultCloud: [{ type: 'autogenerated', dirName: 'commvault/commvault-public-cloud' }],
  Alerts: [{ type: 'autogenerated', dirName: 'operations/monitoring-alerts' }],
  Management: [{ type: 'autogenerated', dirName: 'operations/management' }],
  Ansible: [{ type: 'autogenerated', dirName: 'operations/Ansible' }],
  getStarted: [{ type: 'autogenerated', dirName: 'beginner_guide' }],
  DataBunker: [{ type: 'autogenerated', dirName: 'databunker' }],
  FireOnPrem: [{ type: 'autogenerated', dirName: 'fire/fire-on-prem' }],
  FireAWS: [{ type: 'autogenerated', dirName: 'fire/fire-aws' }],
  Backup: [{ type: 'autogenerated', dirName: 'Dpss_Central_Backup' }],
};

export default sidebars;
